Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Lab_06.Models;
using Microsoft.AspNetCore.Http;

namespace Lab_06.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart _cart;

        public CartSummaryViewComponent(Cart cart)
        {
            _cart = cart;
        }

        public IViewComponentResult Invoke()
        {
            return View(_cart);
        }
    }
}

Components/CommentCardViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Lab_06.Models.ViewModels;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Lab_06.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;

namespace Lab_06.Components
{
    public class CommentCardViewComponent : ViewComponent
    {
        private UserManager<User> _userManager;
        private readonly IHttpContextAccessor _httpContext;
        public CommentCardViewComponent(UserManager<User> userManager, IHttpContextAccessor httpContext)
        {
            _userManager = userManager;
            _httpContext = httpContext;
        }
        public async Task<IViewComponentResult> InvokeAsync(Comment comment)
        {
            User user = await _userManager.GetUserAsync(_httpContext.HttpContext.User);
            return View(new CommentCardViewModel { Comment = comment, User = user});
        }
    }
}

Components/NavigationViewComponent.cs
using Microsoft.AspNetCore.Mvc;
namespace Lab_06.Components
{
    public class NavigationViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            return View();
        }
    }
}

Views/Shared/Components/Navigation/Default.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a asp-action="Index" asp-controller="Home" asp-route-search="" class="navbar-brand">
            Home
        </a>
        <form method="get" asp-action="Index" asp-controller="Home" class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" />
            <button class="btn btn-outline-success" type="submit">
                Search
            </button>
        </form>
        <div>
            @if(User?.Identity?.IsAuthenticated ?? false)
            {
                <div class="container-fluid">
                    <div class="row">
                        <div class="col mt-1">
                            @await Component.InvokeAsync("CartSummary")
                        </div>
                        <div class="col">
                            <div class="dropdown">
                              <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
                                Account
                              </button>
                              <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                                <li><a asp-action="Create"  asp-controller="Videos" class="dropdown-item">Creator panel</a></li>
                                <li><a asp-action="Logout" asp-controller="Account" class="dropdown-item">Log out</a></li>
                                @if ((User?.Identity?.IsAuthenticated ?? false) && (User?.IsInRole("Admin") ?? false))
                                {
                                    <a class="dropdown-item" asp-action="index" asp-controller="Admin">
                                        <i class="fa-solid fa-gears"></i> Admin Settings
                                    </a>
                                }
                              </ul>
                            </div>
                        </div>
                    </div>
                </div>
            }
            else
            {
                <a asp-action="Index" asp-controller="Account" class="btn btn-secondary">Log in</a>
            }
            
        </div>
    </div>
</nav>