Models/Video.cs
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System;

namespace Lab_06.Models
{
    public class Video : IBaseModel
    {
        public int VideoId { get; set; }
        [Required(ErrorMessage = "Please enter a value")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter a value")]
        public string Description { get; set; }
        [Required(ErrorMessage = "Please enter a value")]
        public string ImagePath { get; set; }
        [Required(ErrorMessage = "Please enter a value")]
        public string Path { get; set; }
        [Required(ErrorMessage = "Please enter a value")]
        public string EmbedHtml { get; set; }
        public User User { get; set; }
        public List<LikedVideo> LikedVideo { get; set; }
        public List<VideoGenre> VideoGenres { get; set; }
        public List<Comment> Comments { get; set; }
        [Required(ErrorMessage = "Please enter a value")]
        [Range(0.01, double.MaxValue, ErrorMessage = "Please enter a positive price")]
        public decimal Price { get; set; }
        public bool IsDeleted { get; set; } = false;
        public DateTime CreatedAt { get; set; } = DateTime.Now;

        public DateTime UpdatedAt { get; set; } = DateTime.Now;

    }
}

Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab_06.Data;
using Lab_06.Models;
using Lab_06.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace Lab_06.Controllers
{
    public class VideosController : Controller
    {
        private readonly IVideoRepository _context;
        private IUserRepository _userRepository;
        private UserManager<User> _userManager;
        public int PageSize = 6;

        public VideosController(IVideoRepository context, IUserRepository userRepository, UserManager<User> userManager)
        {
            _context = context;
            _userRepository = userRepository;
            _userManager = userManager;
        }

        // GET: Videos
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Index(int page = 1)
        {
            return View(new VideosIndexViewModels
            {
                Videos = await _context.VideosWithUser
                .OrderBy(el => el.VideoId)
                .Skip((page - 1) * PageSize)
                .Take(PageSize)
                .ToListAsync(),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                    TotalItems = await _context.Videos.CountAsync()
                }
            }); 
        }

        [Authorize]
        public async Task<IActionResult> Create(int videoId)
        {
            Video video = await _context.Videos
            .Include(el => el.User)
            .Include(el => el.Comments)
            .Include(el => el.VideoGenres)
            .FirstOrDefaultAsync(el => el.VideoId == videoId);
            return View(video ?? new Video());
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(Video video)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.GetUserAsync(HttpContext.User);
                if(user == null)
                {
                    return RedirectToAction("Index", "Account");
                }
                video.User = user;
                await _context.SaveVideoAsync(video);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View("Create");
            }
        }

        [HttpPost]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Destroy(int videoId, string returnUrl)
        {
            await _context.DeleteVideoAsync(videoId);
            return Redirect(returnUrl ?? "/");
        }

        // GET: Videos/Play/{id}
        [Authorize]
        public async Task<IActionResult> Play(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            User user = await _userManager.GetUserAsync(HttpContext.User);
            if (user == null)
            {
                return RedirectToAction("Index", "Account");
            }
            List<Video> ownedItems = await _userRepository.GetOwnedContentAsync(user.Id);
            if(!(ownedItems.Where(el => el.VideoId == id).Count() > 0))
            {
                TempData["message"] = "You do not have access to this content! Purchase it to continue";
                return RedirectToAction("Index", "Home");
            }
            Video video = await _context.VideosGetAll
                .Include(el => el.LikedVideo).ThenInclude(el => el.User)
                .FirstOrDefaultAsync(el => el.VideoId == id);
            return View(new PlayVideoViewModel
            {
                Video = video,
                User = await _userManager.GetUserAsync(HttpContext.User),
                IsLike = video.LikedVideo.SingleOrDefault(el => el.User == user)?.IsLike ?? null
            }) ;
        }
    }
}

Views/Videos/Create.cshtml
@model Lab_06.Models.Video

@{
    ViewData["Title"] = "Update";
}

<h4>Create a video!</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post">
            <input type="hidden" asp-for="VideoId" value="@Model?.VideoId" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Path" class="control-label"></label>
                <input asp-for="Path" class="form-control" />
                <span asp-validation-for="Path" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmbedHtml" class="control-label"></label>
                <input asp-for="EmbedHtml" class="form-control" />
                <span asp-validation-for="EmbedHtml" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <button class="btn btn-primary my-1" type="submit">
                    @if(@Model.VideoId > 0)
                    {
                        <span>Update</span>
                    }
                    else
                    {
                        <span>Create</span>
                    }
                </button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Go home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Videos/Index.cshtml
@model Lab_06.Models.ViewModels.VideosIndexViewModels

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>
<table class="table">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Description
            </th>
            <th>
                Date Posted
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Videos) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedAt)
            </td>
            <td>
                <form method="get" asp-action="Create">
                    <input type="hidden" name="videoId" value="@item.VideoId" />
                    <button type="submit" class="btn btn-primary">
                        Update
                    </button>
                </form>
                <form method="post" asp-action="Destroy" asp-controller="Videos">
                    <input type="hidden" name="videoId" value="@item.VideoId" />
                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <button type="submit" class="btn btn-danger">
                        Delete item
                    </button>
                </form>
            </td>
        </tr>
}
    </tbody>
</table>
<div page-model="@Model.PagingInfo" page-action="Index"></div>
<a asp-action="Create" class="btn btn-primary">Create new</a>

Views/Videos/Play.cshtml
@model Lab_06.Models.ViewModels.PlayVideoViewModel

@{
    ViewData["Title"] = Model.Video.Name;
}

<div class="row">
    <div class="container">
        <div class="row">
            <div class="col">
                <h4>@Model.Video.Name</h4>
            </div>
            <div class="col">
                <h5>Posted By: <span class="text-decoration-underline">@Model.Video.User.UserName</span></h5>
            </div>
        </div>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="container-fluid">
            <div class="row">
                <div class="col">
                    @*RAW!*@
                    @Html.Raw(Model.Video.EmbedHtml)
                </div>
            </div>
            <div class="row">
                <div class="col">
                    <div class="row">
                        <div class="col col-6">
                            @if(Model.IsLike == null)
                            {
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col">
                                            <form asp-action="SaveLike" asp-controller="Like" method="post">
                                                <input type="hidden" name="videoId" value="@Model.Video.VideoId" />
                                                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                                <input type="hidden" name="isLike" value="true" />
                                                <button class="btn btn-outline-primary" aria-label="like" type="submit"><i aria-hidden="true" class="fa-solid fa-thumbs-up"></i></button>
                                            </form>
                                            likes @Model.Video.LikedVideo.Where(el => el.IsLike == true).Count()
                                        </div>
                                        <div class="col">
                                            <form asp-action="SaveLike" asp-controller="Like" method="post">
                                                <input type="hidden" name="videoId" value="@Model.Video.VideoId" />
                                                <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                                <input type="hidden" name="isLike" value="false" />
                                                <button class="btn btn-outline-danger" aria-label="dislike" type="submit"><i aria-hidden="true" class="fa-solid fa-thumbs-down"></i></button>
                                            </form>
                                            Dislikes @Model.Video.LikedVideo.Where(el => el.IsLike == false).Count()
                                        </div>
                                    </div>
                                </div>
                            }
                            else
                            {
                                if (Model.IsLike == true)
                                {
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col">
                                                <form asp-action="RemoveLike" asp-controller="Like" method="post">
                                                    <input type="hidden" name="videoId" value="@Model.Video.VideoId" />
                                                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                                    <button class="btn btn-outline-primary" aria-label="like" type="submit"><i aria-hidden="true" class="fa-solid fa-thumbs-up"></i></button>
                                                </form>
                                                likes @Model.Video.LikedVideo.Where(el => el.IsLike == true).Count()
                                            </div>
                                            <div class="col">
                                                <form asp-action="SaveLike" asp-controller="Like" method="post">
                                                    <input type="hidden" name="videoId" value="@Model.Video.VideoId" />
                                                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                                    <input type="hidden" name="isLike" value="false" />
                                                    <button class="btn btn-outline-danger" aria-label="dislike" type="submit"><i aria-hidden="true" class="fa-solid fa-thumbs-down"></i></button>
                                                </form>
                                                Dislikes @Model.Video.LikedVideo.Where(el => el.IsLike == false).Count()
                                            </div>
                                        </div>
                                    </div>
                                }
                                else
                                {
                                    <div class="container-fluid">
                                        <div class="row">
                                            <div class="col">
                                                <form asp-action="SaveLike" asp-controller="Like" method="post">
                                                    <input type="hidden" name="videoId" value="@Model.Video.VideoId" />
                                                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                                    <input type="hidden" name="isLike" value="true" />
                                                    <button class="btn btn-outline-primary" aria-label="like" type="submit"><i aria-hidden="true" class="fa-solid fa-thumbs-up"></i></button>
                                                </form>
                                                likes @Model.Video.LikedVideo.Where(el => el.IsLike == true).Count()
                                            </div>
                                            <div class="col">
                                                <form asp-action="RemoveLike" asp-controller="Like" method="post">
                                                    <input type="hidden" name="videoId" value="@Model.Video.VideoId" />
                                                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                                    <button class="btn btn-outline-danger" aria-label="dislike" type="submit"><i aria-hidden="true" class="fa-solid fa-thumbs-down"></i></button>
                                                </form>
                                                Dislikes @Model.Video.LikedVideo.Where(el => el.IsLike == false).Count()
                                            </div>
                                        </div>
                                    </div>
                                }
                            }

                        </div>
                      </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col">
         <div class="container-fluid">
        <div class="row">
            <div class="col">
                <h5>Comments:</h5>
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col">
                            <div class="ma-1">
                                <form method="post" asp-action="Create" asp-controller="Comments">
                                    <input type="hidden" value="@Model.Video.VideoId" name="videoId" />
                                    <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                                    <label for="text" class="form-label">
                                        Create comment
                                    </label>
                                    <textarea class="form-control" name="text" placeholder="Comment" id="text"></textarea>
                                    <button class="btn btn-primary my-1">
                                        Create comment
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                                @foreach (Comment comment in @Model.Video.Comments.OrderBy(el => el.CreatedAt.TimeOfDay).ToList())
                                {
                                    @await Component.InvokeAsync("CommentCard", comment)
                                }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>